<?php

/**
 * _latte.php: Latte template bridge for ProcessWire.
 *
 * Attempts to render using Latte templates.
 * Falls back to ProcessWire's default PHP templates when no Latte template exists.
 *
 * WARNING: This file is auto-generated and will be overwritten on module updates.
 * Do not edit this file directly.
 */

namespace ProcessWire;

$latte = $modules->get('LatteRenderer');
if ($latte) {
  return $latte->renderPage($page);
}
