<?php

/**
 * _latte.php: Template bridge for ProcessWire + Latte.
 *
 * Handles all page rendering by routing to the LatteRenderer module.
 * Automatically loads Latte templates (.latte) instead of PHP files (.php).
 *
 * WARNING: This file is auto-generated and will be overwritten on module updates.
 * Do not edit this file directly.
 */

namespace ProcessWire;

/** @var LatteRenderer $latte */
$latte = $modules->get('LatteRenderer');

return $latte->renderPage($page);
