<?php

namespace ProcessWire;

require_once __DIR__ . '/LatteEngine.php';

/**
 * LatteRenderer Module
 *
 * Provides Latte template engine integration for ProcessWire.
 * Automatically falls back to PHP templates when no Latte template exists.
 *
 * BASIC INTEGRATION:
 * 
 * Option 1: Use _latte.php (automatic, installed by module)
 * - Works for all pages automatically
 * - Falls back to .php templates when no .latte template exists
 *
 * Option 2: Use in Page classes
 * 
 *   public function ___render($options = [], $options2 = null) {
 *     $latte = $this->wire('modules')->get('LatteRenderer');
 *     return $latte->renderPage($this) ?? parent::___render($options, $options2);
 *   }
 *
 * HOW IT WORKS:
 * - renderPage() checks if Latte template exists
 * - If yes: returns rendered HTML
 * - If no: returns null (signals fallback to ProcessWire's default)
 * - Admin pages are automatically handled by ProcessWire
 *
 * RENDERING METHODS:
 * - renderPage(): Full page with layout
 * - renderBlocks(): Specific blocks only (for partial rendering)
 *
 * SCOPE BUILDING:
 * - buildPageScope() adds all ProcessWire fuel globals automatically
 * - Hook LatteRenderer::buildPageScope to customize variables
 * - setGlobalParams() for project-wide template variables
 *
 * SEPARATION OF CONCERNS:
 * - This module: Renders Latte templates, builds scope, handles fallback
 * - _latte.php: Simple bridge that calls renderPage()
 * - Page classes: Optional integration point for custom logic
 *
 * @property string $layoutFile Path to layout file relative to templates directory
 * @property string $templateDir Directory containing page templates
 */
class LatteRenderer extends WireData implements Module, ConfigurableModule
{
  private ?\Latte\Engine $latte = null;
  private ?LatteEngine $engine = null;

  public static function getModuleInfo()
  {
    return [
      'title' => 'Latte Template Renderer',
      'summary' => 'Latte template engine integration for ProcessWire',
      'version' => '0.0.2',
      'author' => 'Lemachi Narbo',
      'autoload' => true,
      'singular' => true,
      'requires' => 'ProcessWire>=3.0.0',
    ];
  }

  public function init()
  {
    $config = wire('config');

    // Priority: programmatic config > UI config > defaults

    // Layout File - check programmatic config first
    if (isset($config->LatteRenderer['layoutFile'])) {
      $this->layoutFile = $config->LatteRenderer['layoutFile'];
    } elseif (!$this->layoutFile) {
      $this->layoutFile = 'layouts/html.latte';
    }

    // Template Directory - check programmatic config first
    if (isset($config->LatteRenderer['templateDir'])) {
      $this->templateDir = $config->LatteRenderer['templateDir'];
    } elseif (!$this->templateDir) {
      $this->templateDir = 'pages';
    }
  }

  /**
   * Create or update the _latte.php bridge file when module is installed
   */
  public function install()
  {
    $this->createLattePhpBridge();
  }

  /**
   * Create _latte.php bridge file in templates directory
   * 
   * This file checks for Latte templates and falls back to ProcessWire's default behavior if none exist.
   * It is auto-generated and will be overwritten on module updates.
   */
  private function createLattePhpBridge(): void
  {
    $config = $this->wire('config');
    $bridge = $config->paths->templates . '_latte.php';

    $code = '<?php

/**
 * _latte.php: Latte template bridge for ProcessWire.
 *
 * Attempts to render using Latte templates.
 * Falls back to ProcessWire\'s default PHP templates when no Latte template exists.
 *
 * WARNING: This file is auto-generated and will be overwritten on module updates.
 * Do not edit this file directly.
 */

namespace ProcessWire;

$latte = $modules->get(\'LatteRenderer\');
if ($latte) {
  return $latte->renderPage($page);
}
';

    file_put_contents($bridge, $code);
  }

  /**
   * Get or create Latte engine instance
   */
  protected function getLatte(): \Latte\Engine
  {
    if ($this->latte === null) {
      $this->latte = new \Latte\Engine();
      $tempDir = $this->wire('config')->paths->cache . 'latte';
      $this->latte->setTempDirectory($tempDir);
    }
    return $this->latte;
  }

  /**
   * Get or create LatteEngine (rendering orchestrator)
   */
  protected function getEngine(): LatteEngine
  {
    if ($this->engine === null) {
      $config = $this->wire('config');
      $this->engine = new LatteEngine($this->getLatte(), [
        'layout' => $this->resolvePath($this->layoutFile),
        'pagesDir' => $this->resolvePath($this->templateDir),
      ]);
    }
    return $this->engine;
  }

  /**
   * Resolve a path - use as-is if absolute, otherwise prepend templates directory
   *
   * @param string $path Path to resolve
   * @return string Resolved absolute path
   */
  private function resolvePath(string $path): string
  {
    // Check if path is absolute (starts with /)
    if ($path[0] === '/') {
      return $path;
    }
    // Relative path - prepend templates directory
    return $this->wire('config')->paths->templates . $path;
  }

  /**
   * Build standard ProcessWire page scope (hookable)
   *
   * Automatically includes all fuel globals and common page variables.
   * Hook LatteRenderer::buildPageScope to customize variables.
   *
   * @param Page $page
   * @return array
   */
  public function ___buildPageScope(Page $page): array
  {
    $config = $this->wire('config');

    $vars = [
      'config' => $config,
      'urls' => $config->urls,
      'page' => $page,
      'pages' => $this->wire('pages'),
      'user' => $this->wire('user'),
      'input' => $this->wire('input'),
      'sanitizer' => $this->wire('sanitizer'),
      'session' => $this->wire('session'),
      'fields' => $this->wire('fields'),
      'modules' => $this->wire('modules'),
    ];

    // Add all fuel globals (lower priority)
    $vars = array_replace((array) wire('fuel'), $vars);

    return $vars;
  }

  /**
   * Check if a Latte template exists for the given template name
   *
   * @param string $templateName Template name to check
   * @return bool True if Latte template exists
   */
  public function hasLatteTemplate(string $templateName): bool
  {
    return $this->getEngine()->hasTemplate($templateName);
  }

  /**
   * Render full page with layout
   *
   * Returns null when no Latte template exists, allowing fallback to ProcessWire's default PHP templates.
   * Admin pages return empty string (ProcessWire handles them).
   *
   * @param Page $page
   * @return string|null Rendered HTML or null if no Latte template exists
   */
  public function renderPage(Page $page): ?string
  {
    if ($page->template->name === 'admin') {
      return $page->___renderPage();
    }

    // Check if Latte template exists
    if (!$this->hasLatteTemplate($page->template->name)) {
      return null; // No template, signal fallback to ProcessWire's default
    }

    $vars = $this->buildPageScope($page);
    return $this->getEngine()->renderToString($vars);
  }

  /**
   * Set global parameters available to all templates
   *
   * @param array $params
   * @return self
   */
  public function setGlobalParams(array $params): self
  {
    $this->getEngine()->setGlobalParams($params);
    return $this;
  }

  /**
   * Render specific blocks without full page layout
   *
   * Renders blocks from the page template (which inherits from layout).
   * This preserves all CSS, styling context, and inheritance chains.
   *
   * @param Page $page Current page
   * @param array $blockNames Block names to render (e.g., ['header_wrapper', 'main_wrapper'])
   * @return string Concatenated HTML of all requested blocks
   */
  public function renderBlocks(Page $page, array $blockNames): string
  {
    $vars = $this->buildPageScope($page);

    $output = '';
    foreach ($blockNames as $blockName) {
      $output .= $this->getEngine()->renderBlockByTemplate(
        $page->template->name,
        $vars,
        $blockName,
      );
    }

    return $output;
  }

  /**
   * Module configuration
   */
  public static function getModuleConfigInputfields(array $data)
  {
    $inputfields = new InputfieldWrapper();

    // How this module works
    $f = wire('modules')->get('InputfieldMarkup');
    $f->label = 'How This Module Works';
    $f->value =
      '<p>This module installs <strong>_latte.php</strong>, a ProcessWire template bridge that renders Latte templates when available.</p>' .
      '<p><strong>Automatic fallback:</strong> If no <code>.latte</code> template exists for a page, ProcessWire uses the default <code>.php</code> template instead.</p>' .
      '<p><em>Note: _latte.php is auto-generated and will be overwritten on updates.</em></p>' .
      '<hr>' .
      '<p><strong>Configuration:</strong></p>' .
      '<p>Defaults: <code>site/templates/layouts/html.latte</code> and <code>site/templates/pages/</code>.</p>' .
      '<p>Override in <code>config.php</code>:</p>' .
      '<pre>$config->LatteRenderer = [' . "\n" .
      '  "layoutFile" => "layouts/custom.latte",' . "\n" .
      '  "templateDir" => "my-templates"' . "\n" .
      '];</pre>' .
      '<p>Absolute paths are allowed.</p>' .
      '<hr>' .
      '<p><strong>Requirements:</strong> Install Latte via Composer: <code>composer require latte/latte</code></p>';
    $inputfields->add($f);

    // Layout File config
    $f = wire('modules')->get('InputfieldText');
    $f->name = 'layoutFile';
    $f->label = 'Layout File';
    $f->description = 'Path to your main layout file, relative to templates directory (default: layouts/html.latte)';
    $f->value = $data['layoutFile'] ?? 'layouts/html.latte';
    $inputfields->add($f);

    // Template Directory config
    $f = wire('modules')->get('InputfieldText');
    $f->name = 'templateDir';
    $f->label = 'Template Directory';
    $f->description = 'Directory where page templates are stored, relative to templates directory (default: pages)';
    $f->value = $data['templateDir'] ?? 'pages';
    $inputfields->add($f);

    return $inputfields;
  }
}
